/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0 */

#ifndef PB_TILT_GATEWAY_PB_H_INCLUDED
#define PB_TILT_GATEWAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _tiltmsg_colour_type {
    tiltmsg_UNKNOWN = 0,
    tiltmsg_RED = 1,
    tiltmsg_GREEN = 2,
    tiltmsg_BLACK = 3,
    tiltmsg_PURPLE = 4,
    tiltmsg_ORANGE = 5,
    tiltmsg_BLUE = 6,
    tiltmsg_YELLOW = 7,
    tiltmsg_PINK = 8
} tiltmsg_colour_type;

/* Struct definitions */
typedef struct _tiltmsg {
    tiltmsg_colour_type colour;
    float temperature;
    float specificGravity;
    int32_t timeStamp;
} tiltmsg;


/* Helper constants for enums */
#define _tiltmsg_colour_type_MIN tiltmsg_UNKNOWN
#define _tiltmsg_colour_type_MAX tiltmsg_PINK
#define _tiltmsg_colour_type_ARRAYSIZE ((tiltmsg_colour_type)(tiltmsg_PINK+1))
#define tiltmsg_colour_type_UNKNOWN tiltmsg_UNKNOWN
#define tiltmsg_colour_type_RED tiltmsg_RED
#define tiltmsg_colour_type_GREEN tiltmsg_GREEN
#define tiltmsg_colour_type_BLACK tiltmsg_BLACK
#define tiltmsg_colour_type_PURPLE tiltmsg_PURPLE
#define tiltmsg_colour_type_ORANGE tiltmsg_ORANGE
#define tiltmsg_colour_type_BLUE tiltmsg_BLUE
#define tiltmsg_colour_type_YELLOW tiltmsg_YELLOW
#define tiltmsg_colour_type_PINK tiltmsg_PINK


/* Initializer values for message structs */
#define tiltmsg_init_default                     {_tiltmsg_colour_type_MIN, 0, 0, 0}
#define tiltmsg_init_zero                        {_tiltmsg_colour_type_MIN, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define tiltmsg_colour_tag                       1
#define tiltmsg_temperature_tag                  2
#define tiltmsg_specificGravity_tag              3
#define tiltmsg_timeStamp_tag                    4

/* Struct field encoding specification for nanopb */
#define tiltmsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    colour,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    specificGravity,   3) \
X(a, STATIC,   SINGULAR, INT32,    timeStamp,         4)
#define tiltmsg_CALLBACK NULL
#define tiltmsg_DEFAULT NULL

extern const pb_msgdesc_t tiltmsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define tiltmsg_fields &tiltmsg_msg

/* Maximum encoded size of messages (where known) */
#define tiltmsg_size                             23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
