/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_TILT_GATEWAY_PB_H_INCLUDED
#define PB_TILT_GATEWAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _tiltmsg_colour_type {
    tiltmsg_UNKNOWN = 0,
    tiltmsg_RED = 1,
    tiltmsg_GREEN = 2,
    tiltmsg_BLACK = 3,
    tiltmsg_PURPLE = 4,
    tiltmsg_ORANGE = 5,
    tiltmsg_BLUE = 6,
    tiltmsg_YELLOW = 7,
    tiltmsg_PINK = 8
} tiltmsg_colour_type;

/* Struct definitions */
typedef struct _tiltmsg {
    uint32_t version;
    tiltmsg_colour_type colour;
    uint32_t temperature;
    uint32_t specificGravity;
    uint32_t timeStamp;
    uint32_t txPower;
} tiltmsg;


/* Helper constants for enums */
#define _tiltmsg_colour_type_MIN tiltmsg_UNKNOWN
#define _tiltmsg_colour_type_MAX tiltmsg_PINK
#define _tiltmsg_colour_type_ARRAYSIZE ((tiltmsg_colour_type)(tiltmsg_PINK+1))
#define tiltmsg_colour_type_UNKNOWN tiltmsg_UNKNOWN
#define tiltmsg_colour_type_RED tiltmsg_RED
#define tiltmsg_colour_type_GREEN tiltmsg_GREEN
#define tiltmsg_colour_type_BLACK tiltmsg_BLACK
#define tiltmsg_colour_type_PURPLE tiltmsg_PURPLE
#define tiltmsg_colour_type_ORANGE tiltmsg_ORANGE
#define tiltmsg_colour_type_BLUE tiltmsg_BLUE
#define tiltmsg_colour_type_YELLOW tiltmsg_YELLOW
#define tiltmsg_colour_type_PINK tiltmsg_PINK


/* Initializer values for message structs */
#define tiltmsg_init_default                     {0, _tiltmsg_colour_type_MIN, 0, 0, 0, 0}
#define tiltmsg_init_zero                        {0, _tiltmsg_colour_type_MIN, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define tiltmsg_version_tag                      1
#define tiltmsg_colour_tag                       2
#define tiltmsg_temperature_tag                  3
#define tiltmsg_specificGravity_tag              4
#define tiltmsg_timeStamp_tag                    5
#define tiltmsg_txPower_tag                      6

/* Struct field encoding specification for nanopb */
#define tiltmsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, STATIC,   SINGULAR, UENUM,    colour,            2) \
X(a, STATIC,   SINGULAR, UINT32,   temperature,       3) \
X(a, STATIC,   SINGULAR, UINT32,   specificGravity,   4) \
X(a, STATIC,   SINGULAR, UINT32,   timeStamp,         5) \
X(a, STATIC,   SINGULAR, UINT32,   txPower,           6)
#define tiltmsg_CALLBACK NULL
#define tiltmsg_DEFAULT NULL

extern const pb_msgdesc_t tiltmsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define tiltmsg_fields &tiltmsg_msg

/* Maximum encoded size of messages (where known) */
#define tiltmsg_size                             32

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
